<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="EPiServer" />
    <Using Include="EPiServer.Core" />
    <Using Include="EPiServer.DataAbstraction" />
    <Using Include="EPiServer.DataAnnotations" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="EPiServer.CMS" Version="12.33.1" />
    <PackageReference Include="EPiServer.Commerce" Version="14.40.0" />
  </ItemGroup>
  
  <ItemGroup>
    <EmbeddedResource Include="Resources\Translations\**\*" />
  </ItemGroup>
</Project>
